uintptr_t ptr = 0;
int ammo_rifle{};
ReadProcessMemory(hprocess, (LPCVOID)addr, &ptr, sizeof(ptr), NULL);
ReadProcessMemory(hprocess, (LPCVOID)(ptr+0x3D4), &ptr, sizeof(ptr), NULL);
ReadProcessMemory(hprocess, (LPCVOID)(ptr+0x36C), &ptr, sizeof(ptr), NULL);
ReadProcessMemory(hprocess, (LPCVOID)(ptr+0x0), &ammo_rifle, sizeof(ammo_rifle), NULL);
wcout << L"dynamic addrs patrons: " << ptr+0x0 << endl;
wcout << L"old rifle's patron count: " << dec << ammo_rifle << endl;
int leet{1337};
WriteProcessMemory(hprocess, (LPVOID)(ptr+0x0), &leet, sizeof(ptr), NULL);
ReadProcessMemory(hprocess, (LPCVOID)(ptr+0x0), &ammo_rifle, sizeof(ammo_rifle), NULL);
wcout << L"new rifle's patron count: " << dec << ammo_rifle << endl;